repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: format
        name: make format
        pass_filenames: false
        language: system
        entry: make format
      - id: lint
        name: make lint
        pass_filenames: false
        language: system
        entry: make lint
