name: 'Terraform Manager Action'
description: 'Action using Typer CLI'
inputs:
  name:
    description: 'Version of typer'
    required: false
    default: '0.0.2'
runs:
  using: 'composite'
  steps:
    - run: |
        pip install poetry
        poetry install --directory=${{ github.action_path }}
        poetry run tf-mng version
      shell: bash
