name: 'Terraform Manager Action'
description: 'Action using Typer CLI'
inputs:
  tf_mng_command:
    description: 'Command to run with tf-mng'
    required: true
    default: 'version'
runs:
  using: 'composite'
  steps:
    - name: Cache Terraform
      id: cache-terraform
      uses: actions/cache@v2
      with:
        path: ~/.terraform-bin/
        key: terraform-${{ runner.os }}

    - name: Install Terraform
      if: steps.cache-terraform.outputs.cache-hit != 'true'
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform
        mkdir -p ~/.terraform-bin
        sudo cp /usr/bin/terraform ~/.terraform-bin/terraform
      shell: bash

    - name: Restore Cached Terraform
      if: steps.cache-terraform.outputs.cache-hit == 'true'
      run: |
        sudo cp ~/.terraform-bin/terraform /usr/bin/
      shell: bash

    - name: Cache Poetry Dependencies
      id: cache-poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

    - run: |
        pip install poetry
        cd ${{ github.action_path }}
        if [ "${{ steps.cache-poetry.outputs.cache-hit }}" != "true" ]; then
          poetry install
        fi
        poetry run tf-mng ${{ inputs.tf_mng_command }}
      shell: bash
