name: 'Terraform Manager Action'
description: 'Action using Typer CLI'
inputs:
  tf_mng_command:
    description: 'Command to run with tf-mng'
    required: true
    default: 'version'
runs:
  using: 'composite'
  steps:
    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform
      shell: bash

    - run: |
        pip install poetry
        cd ${{ github.action_path }}
        poetry install --
        poetry run tf-mng ${{ inputs.tf_mng_command }}
      shell: bash
