name: 'Terraform Manager Action'
description: 'Action using Typer CLI'
inputs:
  tf_mng_command:
    description: 'Command to run with tf-mng'
    required: true
    default: 'version'
runs:
  using: 'composite'
  steps:
    - run: |
        pip install poetry
        cd ${{ github.action_path }}
        poetry install
        poetry run tf-mng ${{ inputs.tf_mng_command }}
      shell: bash
